### ISSUE TITLE
 JSONException 

### ISSUE THREAD

**Issue by Anvaarulhaq** [TheBotBox/Horoscope-API#3]
Every thing is working fine until I tried to get Weekly, Monthly or Yearly data its throwing an exception that says No value for date .
My Code is 

        Horoscope hGemini = new Horoscope.Zodiac(MainActivity.this)
                .requestSunSign(SUNSIGN.GEMINI)
                .requestDuration(DURATION.WEEK)
                .showLoader(true)
                .isDebuggable(true)
                .fetchHoroscope();
        HorologyController cGemini = new HorologyController(new Response() {
            @Override
            public void onResponseObtained(Zodiac zodiac) {
                String horoscope = zodiac.getHoroscope();
                String sunsign = zodiac.getSunSign();
                String date = zodiac.getDate();
                Log.e("Horoscope", horoscope);
            }

            @Override
            public void onErrorObtained(String errormsg) {
            }
        });
        cGemini.requestConstellations(hGemini);

====>Log message is as bellow

W/System.err: org.json.JSONException: No value for date
W/System.err:     at org.json.JSONObject.get(JSONObject.java:392)
        at org.json.JSONObject.getString(JSONObject.java:553)
        at bot.box.horology.hanshake.HorologyClient$HoroscopeTask.onPostExecute(HorologyClient.java:102)
        at bot.box.horology.hanshake.HorologyClient$HoroscopeTask.onPostExecute(HorologyClient.java:41)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:226)

**Comment by TheBotBox** [comment]
Resolved in <a href='https://bintray.com/boxbotbarry/maven/horoscope-api/_latestVersion'><img src='https://api.bintray.com/packages/boxbotbarry/maven/horoscope-api/images/download.svg'></a>
